### ISSUE TITLE
FileNotFoundError: bootstrap.min.css.map

### ISSUE THREAD

**Issue by spectereye** [thunderbug1/streamlit-javascript#2]
Hi! thanks for your great work!
A error found as below when using it:
FileNotFoundError: [Errno 2] No such file or directory: '...\\.venv\\lib\\site-packages\\streamlit_javascript\\frontend\\build\\bootstrap.min.css.map'

**Comment by thunderbug1** [comment]
I can't really reproduce this issue. When does this occur?

**Comment by ybincholge** [comment]
I faced a same issue
- condition: ubuntu 20.04
- when import & use tree_select component
symptom is now showing tree widget with the code following ..
I hope sombody help me...

`import streamlit as st
from streamlit_tree_select import tree_select


st.title("Initiative Management")
st.write("This page is under construction.")
st.subheader("A simple and elegant checkbox tree for Streamlit.")

nodes = [
    {"label": "Folder A", "value": "folder_a"},
    {
        "label": "Folder B",
        "value": "folder_b",
        "children": [
            {"label": "Sub-folder A", "value": "sub_a"},
            {"label": "Sub-folder B", "value": "sub_b"},
            {"label": "Sub-folder C", "value": "sub_c"},
        ],
    },
    {
        "label": "Folder C",
        "value": "folder_c",
        "children": [
            {"label": "Sub-folder D", "value": "sub_d"},
            {
                "label": "Sub-folder E",
                "value": "sub_e",
                "children": [
                    {"label": "Sub-sub-folder A", "value": "sub_sub_a"},
                    {"label": "Sub-sub-folder B", "value": "sub_sub_b"},
                ],
            },
            {"label": "Sub-folder F", "value": "sub_f"},
        ],
    },
]
return_select = tree_select(nodes)
`


error)
2025-05-03 11:20:59.954 ComponentRequestHandler: GET /home/ybin/project/initiative_mgr/.venv/lib/python3.13/site-packages/streamlit_tree_select/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
  File "/home/ybin/project/initiative_mgr/.venv/lib/python3.13/site-packages/streamlit/web/bootstrap.py", line 347, in run
    if asyncio.get_running_loop().is_running():
       ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ybin/project/initiative_mgr/.venv/lib/python3.13/site-packages/streamlit/web/server/component_request_handler.py", line 56, in get
    with open(abspath, "rb") as file:
         ~~~~^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ybin/project/initiative_mgr/.venv/lib/python3.13/site-packages/streamlit_tree_select/frontend/build/bootstrap.min.css.map'
